@echo off
echo Updating Antigravity Master Inbox...
python "c:\Users\DANIEL\.gemini\antigravity\playground\warped-sojourner\scripts\generate_inbox_index.py"
echo Done! Opening Index...
start "" "c:\Users\DANIEL\.gemini\antigravity\brain\FULL_INBOX_INDEX.md"
